### ISSUE TITLE
Possibly incompatible with PHP v.8+

### ISSUE THREAD

**Issue by mrpsiho** [anthonybudd/WP_Model#13]
Hi!

I have this log record: `PHP Fatal error: Uncaught Error: Non-static method BlogPost::_finderAllinlang() cannot be called statically` and it happens when I switch to PHP 8+. It is about dynamically created methods. With PHP 7.4 it works just fine.

Do you have any solution for this?
Thanks!

**Comment by geniuswebtools** [comment]
@mrpsiho take a look at this.
https://php.watch/versions/8.0/non-static-static-call-fatal-error

I would think you could test this by generating the log for PHP Notices in PHP 7.4, and see if you find the deprecation notice in your log.

**Comment by mrpsiho** [comment]
@geniuswebtools Thanks! I have made all my methods 'static' and now everything works with PHP 8+.
